name: .NET Core WebAPI

on:
  push:
    branches:
    - master
env:
  buildConfiguration: Release
jobs:
  build:
    if: eq(1,1)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: 'dotnet build DotNetCoreWebAPI/WebApplication1.Service/WebApplication1.Service.csproj --configuration ${{ env.buildConfiguration }} '
